spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123qwe
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 3
    host: localhost
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1


